// Approximate unabridged audiobook runtimes. [title, author, hours, minutes, series|null, narrator|null, genre]
// Runtimes vary slightly by edition and retailer, so pages label them "about" and point to the app's own listing.
export const books = [
  ["Project Hail Mary", "Andy Weir", 16, 10, null, "Ray Porter", "science fiction"],
  ["The Martian", "Andy Weir", 10, 53, null, "R.C. Bray", "science fiction"],
  ["Dune", "Frank Herbert", 21, 2, "Dune", "Scott Brick, Orlagh Cassidy and others", "science fiction"],
  ["Ready Player One", "Ernest Cline", 15, 46, null, "Wil Wheaton", "science fiction"],
  ["Ender's Game", "Orson Scott Card", 11, 0, "Ender's Saga", null, "science fiction"],
  ["Hyperion", "Dan Simmons", 15, 0, "Hyperion Cantos", null, "science fiction"],
  ["Neuromancer", "William Gibson", 10, 0, "Sprawl", null, "science fiction"],
  ["Foundation", "Isaac Asimov", 8, 0, "Foundation", null, "science fiction"],
  ["The Hitchhiker's Guide to the Galaxy", "Douglas Adams", 5, 52, "Hitchhiker's Guide", "Stephen Fry", "science fiction"],
  ["Red Rising", "Pierce Brown", 16, 0, "Red Rising", "Tim Gerard Reynolds", "science fiction"],
  ["Dungeon Crawler Carl", "Matt Dinniman", 12, 0, "Dungeon Crawler Carl", "Jeff Hays", "LitRPG"],
  ["Harry Potter and the Sorcerer's Stone", "J.K. Rowling", 8, 17, "Harry Potter", "Jim Dale", "fantasy"],
  ["Harry Potter and the Chamber of Secrets", "J.K. Rowling", 9, 0, "Harry Potter", "Jim Dale", "fantasy"],
  ["Harry Potter and the Prisoner of Azkaban", "J.K. Rowling", 11, 34, "Harry Potter", "Jim Dale", "fantasy"],
  ["Harry Potter and the Goblet of Fire", "J.K. Rowling", 20, 22, "Harry Potter", "Jim Dale", "fantasy"],
  ["Harry Potter and the Order of the Phoenix", "J.K. Rowling", 25, 56, "Harry Potter", "Jim Dale", "fantasy"],
  ["Harry Potter and the Half-Blood Prince", "J.K. Rowling", 19, 0, "Harry Potter", "Jim Dale", "fantasy"],
  ["Harry Potter and the Deathly Hallows", "J.K. Rowling", 21, 50, "Harry Potter", "Jim Dale", "fantasy"],
  ["The Hobbit", "J.R.R. Tolkien", 11, 8, "Middle-earth", "Rob Inglis", "fantasy"],
  ["The Fellowship of the Ring", "J.R.R. Tolkien", 19, 0, "The Lord of the Rings", "Rob Inglis", "fantasy"],
  ["A Game of Thrones", "George R.R. Martin", 33, 51, "A Song of Ice and Fire", "Roy Dotrice", "fantasy"],
  ["The Way of Kings", "Brandon Sanderson", 45, 29, "The Stormlight Archive", "Michael Kramer and Kate Reading", "fantasy"],
  ["Mistborn: The Final Empire", "Brandon Sanderson", 24, 38, "Mistborn", "Michael Kramer", "fantasy"],
  ["The Name of the Wind", "Patrick Rothfuss", 27, 55, "The Kingkiller Chronicle", "Nick Podehl", "fantasy"],
  ["The Eye of the World", "Robert Jordan", 29, 0, "The Wheel of Time", "Michael Kramer and Kate Reading", "fantasy"],
  ["The Lies of Locke Lamora", "Scott Lynch", 22, 0, "Gentleman Bastard", null, "fantasy"],
  ["The Lightning Thief", "Rick Riordan", 10, 0, "Percy Jackson", "Jesse Bernstein", "fantasy"],
  ["The Hunger Games", "Suzanne Collins", 11, 37, "The Hunger Games", "Tatiana Maslany", "dystopian fiction"],
  ["A Court of Thorns and Roses", "Sarah J. Maas", 16, 0, "A Court of Thorns and Roses", null, "romantasy"],
  ["Circe", "Madeline Miller", 10, 0, null, "Perdita Weeks", "mythological fiction"],
  ["The Song of Achilles", "Madeline Miller", 11, 53, null, "Frazer Douglas", "mythological fiction"],
  ["Where the Crawdads Sing", "Delia Owens", 12, 12, null, "Cassandra Campbell", "literary fiction"],
  ["The Midnight Library", "Matt Haig", 8, 50, null, "Carey Mulligan", "fiction"],
  ["The Seven Husbands of Evelyn Hugo", "Taylor Jenkins Reid", 12, 16, null, "Alma Cuervo and Julia Whelan", "historical fiction"],
  ["It Ends with Us", "Colleen Hoover", 8, 0, "It Ends with Us", null, "romance"],
  ["Verity", "Colleen Hoover", 10, 0, null, null, "thriller"],
  ["Lessons in Chemistry", "Bonnie Garmus", 11, 40, null, "Miranda Raison", "historical fiction"],
  ["The Housemaid", "Freida McFadden", 8, 0, "The Housemaid", null, "thriller"],
  ["The Silent Patient", "Alex Michaelides", 8, 43, null, "Jack Hawkins and Louise Brealey", "thriller"],
  ["Gone Girl", "Gillian Flynn", 19, 1, null, "Julia Whelan and Kirby Heyborne", "thriller"],
  ["The Girl on the Train", "Paula Hawkins", 10, 59, null, "Clare Corbett, Louise Brealey and India Fisher", "thriller"],
  ["The Da Vinci Code", "Dan Brown", 17, 0, "Robert Langdon", "Paul Michael", "thriller"],
  ["The Alchemist", "Paulo Coelho", 4, 3, null, "Jeremy Irons", "fiction"],
  ["To Kill a Mockingbird", "Harper Lee", 12, 15, null, "Sissy Spacek", "classic fiction"],
  ["The Great Gatsby", "F. Scott Fitzgerald", 4, 51, null, "Jake Gyllenhaal", "classic fiction"],
  ["Pride and Prejudice", "Jane Austen", 11, 5, null, "Rosamund Pike", "classic fiction"],
  ["1984", "George Orwell", 11, 22, null, "Simon Prebble", "dystopian fiction"],
  ["Frankenstein", "Mary Shelley", 8, 30, null, null, "classic fiction"],
  ["Catch-22", "Joseph Heller", 17, 0, null, "Jay O. Sanders", "classic fiction"],
  ["Moby-Dick", "Herman Melville", 24, 0, null, null, "classic fiction"],
  ["Crime and Punishment", "Fyodor Dostoevsky", 21, 0, null, null, "classic fiction"],
  ["War and Peace", "Leo Tolstoy", 61, 0, null, null, "classic fiction"],
  ["Les Misérables", "Victor Hugo", 60, 0, null, null, "classic fiction"],
  ["The Count of Monte Cristo", "Alexandre Dumas", 52, 0, null, null, "classic fiction"],
  ["Atlas Shrugged", "Ayn Rand", 63, 0, null, "Scott Brick", "fiction"],
  ["Lonesome Dove", "Larry McMurtry", 36, 0, "Lonesome Dove", null, "western"],
  ["It", "Stephen King", 44, 0, null, "Steven Weber", "horror"],
  ["The Stand", "Stephen King", 47, 0, null, "Grover Gardner", "horror"],
  ["Atomic Habits", "James Clear", 5, 35, null, "James Clear", "self-help"],
  ["Sapiens", "Yuval Noah Harari", 15, 17, null, "Derek Perkins", "history"],
  ["Educated", "Tara Westover", 12, 10, null, "Julia Whelan", "memoir"],
  ["Becoming", "Michelle Obama", 19, 3, null, "Michelle Obama", "memoir"],
  ["Born a Crime", "Trevor Noah", 8, 44, null, "Trevor Noah", "memoir"],
  ["Thinking, Fast and Slow", "Daniel Kahneman", 20, 2, null, "Patrick Egan", "psychology"],
  ["Rich Dad Poor Dad", "Robert T. Kiyosaki", 5, 50, null, null, "personal finance"],

  // Added batch 2: runtimes rounded to the nearest hour where exact length is uncertain
  ["Catching Fire", "Suzanne Collins", 11, 0, "The Hunger Games", "Tatiana Maslany", "dystopian fiction"],
  ["Mockingjay", "Suzanne Collins", 11, 0, "The Hunger Games", "Tatiana Maslany", "dystopian fiction"],
  ["The Two Towers", "J.R.R. Tolkien", 17, 0, "The Lord of the Rings", "Rob Inglis", "fantasy"],
  ["The Return of the King", "J.R.R. Tolkien", 14, 0, "The Lord of the Rings", "Rob Inglis", "fantasy"],
  ["A Clash of Kings", "George R.R. Martin", 37, 0, "A Song of Ice and Fire", "Roy Dotrice", "fantasy"],
  ["The Sea of Monsters", "Rick Riordan", 7, 0, "Percy Jackson", "Jesse Bernstein", "fantasy"],
  ["Divergent", "Veronica Roth", 11, 0, "Divergent", null, "dystopian fiction"],
  ["The Fifth Season", "N.K. Jemisin", 14, 0, "The Broken Earth", null, "fantasy"],
  ["Old Man's War", "John Scalzi", 9, 0, "Old Man's War", null, "science fiction"],
  ["Leviathan Wakes", "James S.A. Corey", 20, 0, "The Expanse", null, "science fiction"],
  ["Ancillary Justice", "Ann Leckie", 11, 0, "Imperial Radch", null, "science fiction"],
  ["Children of Time", "Adrian Tchaikovsky", 16, 0, "Children of Time", null, "science fiction"],
  ["The Three-Body Problem", "Cixin Liu", 13, 0, "Remembrance of Earth's Past", null, "science fiction"],
  ["Annihilation", "Jeff VanderMeer", 6, 0, "Southern Reach", null, "science fiction"],
  ["Fahrenheit 451", "Ray Bradbury", 5, 0, null, null, "dystopian fiction"],
  ["Brave New World", "Aldous Huxley", 8, 0, null, null, "dystopian fiction"],
  ["The Handmaid's Tale", "Margaret Atwood", 11, 0, null, null, "dystopian fiction"],
  ["Station Eleven", "Emily St. John Mandel", 9, 0, null, null, "science fiction"],
  ["Piranesi", "Susanna Clarke", 6, 0, null, null, "fantasy"],
  ["The Night Circus", "Erin Morgenstern", 11, 0, null, null, "fantasy"],
  ["American Gods", "Neil Gaiman", 18, 0, null, null, "fantasy"],
  ["Good Omens", "Terry Pratchett and Neil Gaiman", 11, 0, null, null, "fantasy"],
  ["Neverwhere", "Neil Gaiman", 9, 0, null, "Neil Gaiman", "fantasy"],
  ["Coraline", "Neil Gaiman", 3, 0, null, "Neil Gaiman", "fantasy"],
  ["Babel", "R.F. Kuang", 22, 0, null, null, "fantasy"],
  ["The Girl with the Dragon Tattoo", "Stieg Larsson", 16, 0, "Millennium", null, "thriller"],
  ["Big Little Lies", "Liane Moriarty", 13, 0, null, null, "fiction"],
  ["The Kite Runner", "Khaled Hosseini", 12, 0, null, "Khaled Hosseini", "literary fiction"],
  ["A Man Called Ove", "Fredrik Backman", 9, 0, null, null, "fiction"],
  ["Little Fires Everywhere", "Celeste Ng", 12, 0, null, null, "literary fiction"],
  ["The Nightingale", "Kristin Hannah", 17, 0, null, null, "historical fiction"],
  ["All the Light We Cannot See", "Anthony Doerr", 16, 0, null, null, "historical fiction"],
  ["The Book Thief", "Markus Zusak", 14, 0, null, null, "historical fiction"],
  ["Life of Pi", "Yann Martel", 11, 0, null, null, "fiction"],
  ["Of Mice and Men", "John Steinbeck", 3, 0, null, null, "classic fiction"],
  ["The Catcher in the Rye", "J.D. Salinger", 7, 0, null, null, "classic fiction"],
  ["Lord of the Flies", "William Golding", 6, 0, null, null, "classic fiction"],
  ["Jane Eyre", "Charlotte Brontë", 19, 0, null, null, "classic fiction"],
  ["Wuthering Heights", "Emily Brontë", 11, 0, null, null, "classic fiction"],
  ["Little Women", "Louisa May Alcott", 16, 0, null, null, "classic fiction"],
  ["Anne of Green Gables", "L.M. Montgomery", 9, 0, "Anne of Green Gables", null, "classic fiction"],
  ["Dracula", "Bram Stoker", 15, 0, null, null, "classic horror"],
  ["The Hound of the Baskervilles", "Arthur Conan Doyle", 6, 0, "Sherlock Holmes", null, "mystery"],
  ["Alice's Adventures in Wonderland", "Lewis Carroll", 3, 0, null, null, "classic fiction"],
  ["Treasure Island", "Robert Louis Stevenson", 8, 0, null, null, "classic fiction"],
  ["The Picture of Dorian Gray", "Oscar Wilde", 8, 0, null, null, "classic fiction"],
  ["Great Expectations", "Charles Dickens", 18, 0, null, null, "classic fiction"],
  ["A Tale of Two Cities", "Charles Dickens", 12, 0, null, null, "classic fiction"],
  ["Anna Karenina", "Leo Tolstoy", 35, 0, null, null, "classic fiction"],
  ["The Brothers Karamazov", "Fyodor Dostoevsky", 37, 0, null, null, "classic fiction"],
  ["Don Quixote", "Miguel de Cervantes", 40, 0, null, null, "classic fiction"],
  ["Ulysses", "James Joyce", 27, 0, null, null, "classic fiction"],
  ["Gone with the Wind", "Margaret Mitchell", 49, 0, null, null, "historical fiction"],
  ["Rebecca", "Daphne du Maurier", 12, 0, null, null, "classic fiction"],
  ["And Then There Were None", "Agatha Christie", 6, 0, null, null, "mystery"],
  ["Murder on the Orient Express", "Agatha Christie", 6, 0, "Hercule Poirot", null, "mystery"],
  ["The Shining", "Stephen King", 17, 0, "The Shining", null, "horror"],
  ["Carrie", "Stephen King", 6, 0, null, null, "horror"],
  ["The Road", "Cormac McCarthy", 6, 0, null, null, "literary fiction"],
  ["Normal People", "Sally Rooney", 7, 0, null, null, "literary fiction"],
  ["The Thursday Murder Club", "Richard Osman", 12, 0, "Thursday Murder Club", null, "mystery"],
  ["Daisy Jones & the Six", "Taylor Jenkins Reid", 9, 0, null, null, "historical fiction"],
  ["Tomorrow, and Tomorrow, and Tomorrow", "Gabrielle Zevin", 15, 0, null, null, "literary fiction"],
  ["Remarkably Bright Creatures", "Shelby Van Pelt", 10, 0, null, null, "fiction"],
  ["A Short History of Nearly Everything", "Bill Bryson", 18, 0, null, null, "science"],
  ["Outliers", "Malcolm Gladwell", 7, 0, null, "Malcolm Gladwell", "nonfiction"],
  ["The Tipping Point", "Malcolm Gladwell", 6, 0, null, "Malcolm Gladwell", "nonfiction"],
  ["Blink", "Malcolm Gladwell", 6, 0, null, "Malcolm Gladwell", "nonfiction"],
  ["Talking to Strangers", "Malcolm Gladwell", 8, 0, null, "Malcolm Gladwell", "nonfiction"],
  ["Quiet", "Susan Cain", 11, 0, null, null, "psychology"],
  ["Grit", "Angela Duckworth", 6, 0, null, "Angela Duckworth", "psychology"],
  ["Deep Work", "Cal Newport", 7, 0, null, null, "productivity"],
  ["Essentialism", "Greg McKeown", 6, 0, null, null, "productivity"],
  ["The 7 Habits of Highly Effective People", "Stephen R. Covey", 13, 0, null, null, "self-help"],
  ["How to Win Friends and Influence People", "Dale Carnegie", 7, 0, null, null, "self-help"],
  ["The Power of Habit", "Charles Duhigg", 10, 0, null, null, "psychology"],
  ["Mindset", "Carol S. Dweck", 10, 0, null, null, "psychology"],
  ["Man's Search for Meaning", "Viktor E. Frankl", 4, 0, null, null, "psychology"],
  ["The Subtle Art of Not Giving a F*ck", "Mark Manson", 5, 0, null, "Roger Wayne", "self-help"],
  ["12 Rules for Life", "Jordan B. Peterson", 15, 0, null, "Jordan B. Peterson", "self-help"],
  ["Can't Hurt Me", "David Goggins", 13, 0, null, null, "memoir"],
  ["Homo Deus", "Yuval Noah Harari", 14, 0, null, null, "history"],
  ["21 Lessons for the 21st Century", "Yuval Noah Harari", 12, 0, null, null, "history"],
  ["Guns, Germs, and Steel", "Jared Diamond", 16, 0, null, null, "history"],
  ["The Psychology of Money", "Morgan Housel", 5, 0, null, null, "personal finance"],
  ["Zero to One", "Peter Thiel", 5, 0, null, null, "business"],
  ["The Lean Startup", "Eric Ries", 8, 0, null, null, "business"],
  ["Steve Jobs", "Walter Isaacson", 25, 0, null, null, "biography"],
  ["Shoe Dog", "Phil Knight", 12, 0, null, "Norbert Leo Butz", "memoir"],
  ["Greenlights", "Matthew McConaughey", 7, 0, null, "Matthew McConaughey", "memoir"],
  ["Unbroken", "Laura Hillenbrand", 14, 0, null, null, "history"],
  ["Into the Wild", "Jon Krakauer", 7, 0, null, null, "nonfiction"],
  ["Into Thin Air", "Jon Krakauer", 9, 0, null, null, "nonfiction"],
  ["The Immortal Life of Henrietta Lacks", "Rebecca Skloot", 12, 0, null, null, "science"],
  ["Bad Blood", "John Carreyrou", 13, 0, null, null, "nonfiction"],
  ["Killers of the Flower Moon", "David Grann", 9, 0, null, null, "history"],
  ["In Cold Blood", "Truman Capote", 13, 0, null, null, "true crime"],
  ["Spare", "Prince Harry", 15, 0, null, "Prince Harry", "memoir"],
  ["Eat Pray Love", "Elizabeth Gilbert", 13, 0, null, "Elizabeth Gilbert", "memoir"],
  ["Bossypants", "Tina Fey", 5, 0, null, "Tina Fey", "memoir"],
  ["Why We Sleep", "Matthew Walker", 13, 0, null, null, "science"],
  ["Range", "David Epstein", 11, 0, null, null, "nonfiction"],
  ["A Brief History of Time", "Stephen Hawking", 5, 0, null, null, "science"],
  ["Astrophysics for People in a Hurry", "Neil deGrasse Tyson", 4, 0, null, "Neil deGrasse Tyson", "science"],
];

export function slugify(s) {
  return s.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/['’]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}
