// Approximate unabridged audiobook runtimes. [title, author, hours, minutes, series|null, narrator|null, genre]
// Runtimes vary slightly by edition and retailer, so pages label them "about" and point to the app's own listing.
export const books = [
  ["Project Hail Mary", "Andy Weir", 16, 10, null, "Ray Porter", "science fiction"],
  ["The Martian", "Andy Weir", 10, 53, null, "R.C. Bray", "science fiction"],
  ["Dune", "Frank Herbert", 21, 2, "Dune", "Scott Brick, Orlagh Cassidy and others", "science fiction"],
  ["Ready Player One", "Ernest Cline", 15, 46, null, "Wil Wheaton", "science fiction"],
  ["Ender's Game", "Orson Scott Card", 11, 0, "Ender's Saga", null, "science fiction"],
  ["Hyperion", "Dan Simmons", 15, 0, "Hyperion Cantos", null, "science fiction"],
  ["Neuromancer", "William Gibson", 10, 0, "Sprawl", null, "science fiction"],
  ["Foundation", "Isaac Asimov", 8, 0, "Foundation", null, "science fiction"],
  ["The Hitchhiker's Guide to the Galaxy", "Douglas Adams", 5, 52, "Hitchhiker's Guide", "Stephen Fry", "science fiction"],
  ["Red Rising", "Pierce Brown", 16, 0, "Red Rising", "Tim Gerard Reynolds", "science fiction"],
  ["Dungeon Crawler Carl", "Matt Dinniman", 12, 0, "Dungeon Crawler Carl", "Jeff Hays", "LitRPG"],
  ["Harry Potter and the Sorcerer's Stone", "J.K. Rowling", 8, 17, "Harry Potter", "Jim Dale", "fantasy"],
  ["Harry Potter and the Chamber of Secrets", "J.K. Rowling", 9, 0, "Harry Potter", "Jim Dale", "fantasy"],
  ["Harry Potter and the Prisoner of Azkaban", "J.K. Rowling", 11, 34, "Harry Potter", "Jim Dale", "fantasy"],
  ["Harry Potter and the Goblet of Fire", "J.K. Rowling", 20, 22, "Harry Potter", "Jim Dale", "fantasy"],
  ["Harry Potter and the Order of the Phoenix", "J.K. Rowling", 25, 56, "Harry Potter", "Jim Dale", "fantasy"],
  ["Harry Potter and the Half-Blood Prince", "J.K. Rowling", 19, 0, "Harry Potter", "Jim Dale", "fantasy"],
  ["Harry Potter and the Deathly Hallows", "J.K. Rowling", 21, 50, "Harry Potter", "Jim Dale", "fantasy"],
  ["The Hobbit", "J.R.R. Tolkien", 11, 8, "Middle-earth", "Rob Inglis", "fantasy"],
  ["The Fellowship of the Ring", "J.R.R. Tolkien", 19, 0, "The Lord of the Rings", "Rob Inglis", "fantasy"],
  ["A Game of Thrones", "George R.R. Martin", 33, 51, "A Song of Ice and Fire", "Roy Dotrice", "fantasy"],
  ["The Way of Kings", "Brandon Sanderson", 45, 29, "The Stormlight Archive", "Michael Kramer and Kate Reading", "fantasy"],
  ["Mistborn: The Final Empire", "Brandon Sanderson", 24, 38, "Mistborn", "Michael Kramer", "fantasy"],
  ["The Name of the Wind", "Patrick Rothfuss", 27, 55, "The Kingkiller Chronicle", "Nick Podehl", "fantasy"],
  ["The Eye of the World", "Robert Jordan", 29, 0, "The Wheel of Time", "Michael Kramer and Kate Reading", "fantasy"],
  ["The Lies of Locke Lamora", "Scott Lynch", 22, 0, "Gentleman Bastard", null, "fantasy"],
  ["The Lightning Thief", "Rick Riordan", 10, 0, "Percy Jackson", "Jesse Bernstein", "fantasy"],
  ["The Hunger Games", "Suzanne Collins", 11, 37, "The Hunger Games", "Tatiana Maslany", "dystopian fiction"],
  ["A Court of Thorns and Roses", "Sarah J. Maas", 16, 0, "A Court of Thorns and Roses", null, "romantasy"],
  ["Circe", "Madeline Miller", 10, 0, null, "Perdita Weeks", "mythological fiction"],
  ["The Song of Achilles", "Madeline Miller", 11, 53, null, "Frazer Douglas", "mythological fiction"],
  ["Where the Crawdads Sing", "Delia Owens", 12, 12, null, "Cassandra Campbell", "literary fiction"],
  ["The Midnight Library", "Matt Haig", 8, 50, null, "Carey Mulligan", "fiction"],
  ["The Seven Husbands of Evelyn Hugo", "Taylor Jenkins Reid", 12, 16, null, "Alma Cuervo and Julia Whelan", "historical fiction"],
  ["It Ends with Us", "Colleen Hoover", 8, 0, "It Ends with Us", null, "romance"],
  ["Verity", "Colleen Hoover", 10, 0, null, null, "thriller"],
  ["Lessons in Chemistry", "Bonnie Garmus", 11, 40, null, "Miranda Raison", "historical fiction"],
  ["The Housemaid", "Freida McFadden", 8, 0, "The Housemaid", null, "thriller"],
  ["The Silent Patient", "Alex Michaelides", 8, 43, null, "Jack Hawkins and Louise Brealey", "thriller"],
  ["Gone Girl", "Gillian Flynn", 19, 1, null, "Julia Whelan and Kirby Heyborne", "thriller"],
  ["The Girl on the Train", "Paula Hawkins", 10, 59, null, "Clare Corbett, Louise Brealey and India Fisher", "thriller"],
  ["The Da Vinci Code", "Dan Brown", 17, 0, "Robert Langdon", "Paul Michael", "thriller"],
  ["The Alchemist", "Paulo Coelho", 4, 3, null, "Jeremy Irons", "fiction"],
  ["To Kill a Mockingbird", "Harper Lee", 12, 15, null, "Sissy Spacek", "classic fiction"],
  ["The Great Gatsby", "F. Scott Fitzgerald", 4, 51, null, "Jake Gyllenhaal", "classic fiction"],
  ["Pride and Prejudice", "Jane Austen", 11, 5, null, "Rosamund Pike", "classic fiction"],
  ["1984", "George Orwell", 11, 22, null, "Simon Prebble", "dystopian fiction"],
  ["Frankenstein", "Mary Shelley", 8, 30, null, null, "classic fiction"],
  ["Catch-22", "Joseph Heller", 17, 0, null, "Jay O. Sanders", "classic fiction"],
  ["Moby-Dick", "Herman Melville", 24, 0, null, null, "classic fiction"],
  ["Crime and Punishment", "Fyodor Dostoevsky", 21, 0, null, null, "classic fiction"],
  ["War and Peace", "Leo Tolstoy", 61, 0, null, null, "classic fiction"],
  ["Les Misérables", "Victor Hugo", 60, 0, null, null, "classic fiction"],
  ["The Count of Monte Cristo", "Alexandre Dumas", 52, 0, null, null, "classic fiction"],
  ["Atlas Shrugged", "Ayn Rand", 63, 0, null, "Scott Brick", "fiction"],
  ["Lonesome Dove", "Larry McMurtry", 36, 0, "Lonesome Dove", null, "western"],
  ["It", "Stephen King", 44, 0, null, "Steven Weber", "horror"],
  ["The Stand", "Stephen King", 47, 0, null, "Grover Gardner", "horror"],
  ["Atomic Habits", "James Clear", 5, 35, null, "James Clear", "self-help"],
  ["Sapiens", "Yuval Noah Harari", 15, 17, null, "Derek Perkins", "history"],
  ["Educated", "Tara Westover", 12, 10, null, "Julia Whelan", "memoir"],
  ["Becoming", "Michelle Obama", 19, 3, null, "Michelle Obama", "memoir"],
  ["Born a Crime", "Trevor Noah", 8, 44, null, "Trevor Noah", "memoir"],
  ["Thinking, Fast and Slow", "Daniel Kahneman", 20, 2, null, "Patrick Egan", "psychology"],
  ["Rich Dad Poor Dad", "Robert T. Kiyosaki", 5, 50, null, null, "personal finance"],
];

export function slugify(s) {
  return s.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/['’]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}
